ICV_HOME_DIR      = /mnt/vol_synopsys2023/synopsys/icvalidator/U-2022.12-SP4
ICV_COORDS_BIT    = 32
WORKING_DIR       = .
INLIB             = fx4
INLIB_PATH        = 
BLOCK             = fx4_sc
CREATE_VUE_OUTPUT = TRUE
PYDB_PATH         = pydb
RUN_DETAILS_DIR   = run_details
NDB_PATH          = run_details/.ndb
REPORT_LAYOUT_ERRORS = TOP
FORMAT            = OPENACCESS
SCHEMATIC_FORMAT  = ICV
GROUP_PATH        = run_details/group
RUNSET_FILE_NAME  = xt018_1243_DRC_LP5MOS_MET4_METMID_METTHK.drc.rs
